/**
 * 
 * ek9000 CoE Configurator - Easily configure CoE options through the EK9K
 * 
 */ 
#pragma once

#include "drvEK9000.h"

typedef struct coe_param_s
{
	const char* name;
	const char* unit;
	unsigned int index;
	unsigned int subindex;
	enum 
	{
		COE_PARAM_INT8,
		COE_PARAM_INT16,
		COE_PARAM_INT32,
		COE_PARAM_INT64,
		COE_PARAM_STRING, 
		COE_PARAM_FLOAT32,
		COE_PARAM_FLOAT64,
	} type;
	int length; /* Only if a string */
} coe_param_t;

#include "autogenerated_params.h"

template<class T>
void coeSetParameter(drvEK9000* ek, coe_param_t param, int terminal, T value);
void coeSetStringParameter(drvEK9000* ek, coe_param_t param, int terminal, const char* string);

template<class T>
void coeReadParameter(drvEK9000* ek, coe_param_t param, int terminal, T& outval);
void coeReadString(drvEK9000* ek, coe_param_t param, int terminal, char* outbuf, int len);